### ISSUE TITLE
Problem in tokenizer

### ISSUE THREAD

**Issue by MohamedRaafat188** [salaniz/pycocoevalcap#16]
when I run the code in the coco_eval_example.py file It gave me the following error:
Traceback (most recent call last):
  File "d:/Udacity/CVND_Exercises/P2_Image_Captioning/demo.py", line 21, in <module>
    coco_eval.evaluate()
  File "d:\Udacity\CVND_Exercises\P2_Image_Captioning\pycocoevalcap\eval.py", line 33, in evaluate
    gts  = tokenizer.tokenize(gts)
  File "d:\Udacity\CVND_Exercises\P2_Image_Captioning\pycocoevalcap\tokenizer\ptbtokenizer.py", line 55, in tokenize
    p_tokenizer = subprocess.Popen(cmd, cwd=path_to_jar_dirname, stdout=subprocess.PIPE)
  File "C:\Users\user\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Can anyone help me please. And thank you in advance.

**Comment by wyh2000** [comment]
Yes, I have the same problem. Looking forward to more explanation.

**Comment by wyh2000** [comment]
> Yes, I have the same problem. Looking forward to more explanation.

I install java-1.8.0, then it works.
